# Generated by Django 4.1.4 on 2022-12-24 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ('top_position', 'lvl', 'position'), 'verbose_name': 'Пункт меню', 'verbose_name_plural': 'Пункты меню'},
        ),
        migrations.AddField(
            model_name='menu',
            name='lvl',
            field=models.PositiveIntegerField(default=0, verbose_name='Уровень'),
        ),
        migrations.AddField(
            model_name='menu',
            name='top_position',
            field=models.PositiveIntegerField(default=0, verbose_name='Позиция главного пункта'),
        ),
    ]
