# Generated by Django 4.1.4 on 2022-12-26 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_menu_bname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='bname',
        ),
    ]
