# Generated by Django 4.1.4 on 2022-12-26 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0005_remove_menu_bname'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='menus.menu'),
        ),
    ]
