# Generated by Django 4.1.4 on 2022-12-26 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0006_menu_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='child',
        ),
        migrations.AddField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='menus.menu'),
        ),
    ]
